apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-auth
  namespace: firsteps-dev
spec:
  selector:
    matchLabels:
      app: ms-auth
  replicas: 1
  template:
    metadata:
      labels:
         app: ms-auth
    spec:
      imagePullSecrets:
         - name: github-secret
      containers:
         - name: ms-auth
           image: ghcr.io/juangomez0303/ms-authentication:latest
           ports:
              - containerPort: 8080
           env:
              - name: db_host
                valueFrom:
                  configMapKeyRef:
                    name:  variables-entorno
                    key: db_host
              - name: db_usuario
                valueFrom:
                  configMapKeyRef:
                    name:  variables-entorno
                    key: db_usuario
              - name: db_contrasena
                valueFrom:
                  configMapKeyRef:
                    name:  variables-entorno
                    key: db_contrasena
              - name: db_basedatos_ms-auth
                valueFrom:
                  configMapKeyRef:
                    name:  variables-entorno
                    key: db_basedatos_ms-auth
              - name: autorizacion_urlAutorizacion
                valueFrom:
                  configMapKeyRef:
                    name:  variables-entorno
                    key: autorizacion_urlAutorizacion
              - name: autorizacion_urlAutorizacionBase
                valueFrom:
                  configMapKeyRef:
                    name:  variables-entorno
                    key: autorizacion_urlAutorizacionBase
              - name: autorizacion_urlAutorizacionUsuario
                valueFrom:
                  configMapKeyRef:
                    name:  variables-entorno
                    key: autorizacion_urlAutorizacionUsuario
              - name: autorizacion_urlAutorizacionAplicacion
                valueFrom:
                  configMapKeyRef:
                    name:  variables-entorno
                    key: autorizacion_urlAutorizacionAplicacion
              - name: archivos_url
                valueFrom:
                  configMapKeyRef:
                    name:  variables-entorno
                    key: archivos_url
              - name: datos_url
                valueFrom:
                  configMapKeyRef:
                    name:  variables-entorno
                    key: datos_url
              - name: autorizacion_codigo_ms-auth
                valueFrom:
                  configMapKeyRef:
                    name:  variables-entorno
                    key: autorizacion_codigo_ms-auth
              - name: casos_url
                valueFrom:
                  configMapKeyRef:
                    name:  variables-entorno
                    key: casos_url
              - name: contabilidad_url
                valueFrom:
                  configMapKeyRef:
                    name:  variables-entorno
                    key: contabilidad_url
              - name: facturas_url
                valueFrom:
                  configMapKeyRef:
                    name:  variables-entorno
                    key: facturas_url
              - name: gastos_url
                valueFrom:
                  configMapKeyRef:
                    name:  variables-entorno
                    key: gastos_url
              - name: ingresoNoOperacional_url
                valueFrom:
                  configMapKeyRef:
                    name:  variables-entorno
                    key: ingresoNoOperacional_url
              - name: nomina_url
                valueFrom:
                  configMapKeyRef:
                    name:  variables-entorno
                    key: nomina_url
              - name: sucursales_url
                valueFrom:
                  configMapKeyRef:
                    name:  variables-entorno
                    key: sucursales_url
              - name: terceros_url
                valueFrom:
                  configMapKeyRef:
                    name:  variables-entorno
                    key: terceros_url
              - name: cajaCuentaBancos_url
                valueFrom:
                  configMapKeyRef:
                    name:  variables-entorno
                    key: cajaCuentaBancos_url
              - name: impuestos_url
                valueFrom:
                  configMapKeyRef:
                    name:  variables-entorno
                    key: impuestos_url
              - name: URL_AUTH_APP
                valueFrom:
                  configMapKeyRef:
                    name:  variables-entorno
                    key: URL_AUTH_APP
              - name: URL_AUTH
                valueFrom:
                  configMapKeyRef:
                    name:  variables-entorno
                    key: URL_AUTH
---
apiVersion: v1
kind: Service
metadata:
  name: ms-auth
  namespace: firsteps-dev
spec:
#  type: NodePort
  selector:
    app: ms-auth
  ports:
    - protocol: TCP
      port: 8080
#      nodePort: 30001
      targetPort: 8080