spring.application.name=MS-Authentication

spring.datasource.url=jdbc:postgresql://192.168.0.131:5432/users_db
spring.datasource.username=admin
# spring.datasource.username=admin
spring.datasource.password=tesis123
# spring.datasource.password=tesis123
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update

# Use JDBC-backed Spring Session and initialize its schema on startup
spring.session.store-type=jdbc
spring.session.jdbc.initialize-schema=always

# Allow Spring's SQL initializer to run against non-embedded databases
spring.sql.init.mode=always

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=firstepsapp@gmail.com
spring.mail.password=dsyg jrxj uisv crqg
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true