spring.application.name=MS-Authentication

spring.datasource.url=jdbc:postgresql://192.168.0.134:5432/users_db
spring.datasource.username=admin
spring.datasource.password=tesis123
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update